import { NodeEnv } from 'src/common/enums';

export const APP_DEFAULTS = {
  NODE_ENV: NodeEnv.Local,
  APP_NAME: 'LMS Quiz',
  APP_PORT: 3000,
  ACCESS_TOKEN_EXPIRES_IN: '1d',
  REFRESH_TOKEN_EXPIRES_IN: '30d',
  RESET_PASSWORD_EXPIRES_IN: '30m',
  VERIFY_EMAIL_EXPIRES_IN: '30m',
  DATE_FORMAT: 'YYYY-MM-DD',
  DATE_FORMAT_V2: 'DD MMM YYYY',
  DATE_TIME_FORMAT: 'YYYY-MM-DD HH:mm:ss',
  TIME_FORMAT: 'HH:mm:ss',
  HOUR_FORMAT: 'h:mm A',
  PAGINATION: {
    PAGE_DEFAULT: 1,
    LIMIT_DEFAULT: 10,
    SORT_BY_DEFAULT: 'id',
    ORDER_BY_DEFAULT: 'DESC',
  },
  VERIFY_OTP_EXPIRES_IN: '10m',
  OTP_COOLDOWN: 60000,
  PASSWORD_LENGTH: 8,
};
