export enum IntentType {
  QUERY_INVENTORY = 'QUERY_INVENTORY',
  QUERY_ORDER = 'QUERY_ORDER',
  QUERY_MANUFACTURE = 'QUERY_MANUFACTURE',
  CREATE_TICKET = 'CREATE_TICKET',
  REPORT = 'REPORT',
  GUIDE = 'GUIDE',
  GREETING = 'GREETING',
  UNKNOWN = 'UNKNOWN',
}

export enum EntityType {
  PRODUCT = 'PRODUCT',
  WAREHOUSE = 'WAREHOUSE',
  ORDER_ID = 'ORDER_ID',
  DATE = 'DATE',
  QUANTITY = 'QUANTITY',
}
